[version]
required-game-version = "1.0.10b"
plugin-version = "0.6.2"

[version-hash]
"1.0.9b" = "i dont know hash of this version"
"1.0.10b" = "597baead816b32429c2ea9ac5f340ae8"

[replace]
"res://Core/Combat.gde" = "Core/Combat.gde"
"res://Core/Game.gde" = "Core/Game.gde"
"res://Core/Inventory.gde" = "Core/Inventory.gde"
"res://Core/RunDatabase.gde" = "Core/RunDatabase.gde"
"res://Core/Shop.gde" = "Core/Shop.gde"

"res://Interface/BuildHistory/BuildEntry.gde" = "Interface/BuildHistory/BuildEntry.gde"
"res://Interface/BuildHistory/BuildEntryPlaceholder.gde" = "Interface/BuildHistory/BuildEntryPlaceholder.gde"
"res://Interface/BuildHistory/BuildHistory.gde" = "Interface/BuildHistory/BuildHistory.gde"
"res://Interface/BuildHistory/BuildHistoryData.gde" = "Interface/BuildHistory/BuildHistoryData.gde"
"res://Interface/BuildHistory/RoundResultButton.gde" = "Interface/BuildHistory/RoundResultButton.gde"
"res://Interface/BuildHistory/OpponentPoolAdapter.gde" = "Interface/BuildHistory/OpponentPoolAdapter.gde"
"res://Interface/BuildHistory/OpponentPoolAdapter.gd.remap" = "Interface/BuildHistory/OpponentPoolAdapter.gd.remap"
"res://Interface/BuildHistory/BuildHistory.tscn" = "Interface/BuildHistory/BuildHistory.tscn"

"res://Interface/EditModeButtons.gde" = "Interface/EditModeButtons.gde"
"res://Interface/IngameCharacterHUD.gde" = "Interface/IngameCharacterHUD.gde"
"res://Interface/Lobbies/CustomUnrankedUI.gde" = "Interface/Lobbies/CustomUnrankedUI.gde"
"res://Interface/Lobbies/OtherModesUI.tscn" = "Interface/Lobbies/OtherModesUI.tscn"
"res://Interface/OpponentRankDisplay.gde" = "Interface/OpponentRankDisplay.gde"
"res://Interface/OpponentRankDisplay.gd.remap" = "Interface/OpponentRankDisplay.gd.remap"
"res://Interface/OpponentRankDisplay.tscn" = "Interface/OpponentRankDisplay.tscn"
"res://Interface/PatchNotes.gde" = "Interface/PatchNotes.gde"
"res://Interface/PatchNotes.tscn" = "Interface/PatchNotes.tscn"
"res://Interface/PushToStorageButton.gde" = "Interface/PushToStorageButton.gde"
"res://Interface/RarityHint.gde" = "Interface/RarityHint.gde"
"res://Interface/ShopRarityChart.gde" = "Interface/ShopRarityChart.gde"
"res://Interface/ShopToolbar.gde" = "Interface/ShopToolbar.gde"
"res://Interface/Tooltips/ItemTooltip.gde" = "Interface/Tooltips/ItemTooltip.gde"

"res://Items/Item.gde" = "Items/Item.gde"

"res://Utility/BuildHistoryDB.gde" = "Utility/BuildHistoryDB.gde"
"res://Utility/CustomRules.gde" = "Utility/CustomRules.gde"
"res://Utility/RunData.gde" = "Utility/RunData.gde"
"res://Utility/RunData.gd.remap" = "Utility/RunData.gd.remap"

"res://Assets/Combat.png" = "Assets/Combat.png"
"res://Assets/Combat.png.import" = "Assets/Combat.png.import"
"res://Assets/Copy.png" = "Assets/Copy.png"
"res://Assets/Copy.png.import" = "Assets/Copy.png.import"

"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex" = ".import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex"
"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5" = ".import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex" = ".import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5" = ".import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5"

# "res://project.binary" = "project.binary"
