[version]
required-game-version = "1.0.10b"
plugin-version = "0.6.1"

[version-hash]
"1.0.9b" = "i dont know hash of this version"
"1.0.10b" = "597baead816b32429c2ea9ac5f340ae8"

[replace]
"res://Core/Combat.gde" = "../assets/Core/Combat.gde"
"res://Core/Game.gde" = "../assets/Core/Game.gde"
"res://Core/Inventory.gde" = "../assets/Core/Inventory.gde"
"res://Core/RunDatabase.gde" = "../assets/Core/RunDatabase.gde"
"res://Core/Shop.gde" = "../assets/Core/Shop.gde"

"res://Interface/BuildHistory/BuildEntry.gde" = "../assets/Interface/BuildHistory/BuildEntry.gde"
"res://Interface/BuildHistory/BuildEntryPlaceholder.gde" = "../assets/Interface/BuildHistory/BuildEntryPlaceholder.gde"
"res://Interface/BuildHistory/BuildHistory.gde" = "../assets/Interface/BuildHistory/BuildHistory.gde"
"res://Interface/BuildHistory/BuildHistoryData.gde" = "../assets/Interface/BuildHistory/BuildHistoryData.gde"
"res://Interface/BuildHistory/RoundResultButton.gde" = "../assets/Interface/BuildHistory/RoundResultButton.gde"
"res://Interface/BuildHistory/OpponentPoolAdapter.gde" = "../assets/Interface/BuildHistory/OpponentPoolAdapter.gde"
"res://Interface/BuildHistory/OpponentPoolAdapter.gd.remap" = "../assets/Interface/BuildHistory/OpponentPoolAdapter.gd.remap"
"res://Interface/BuildHistory/BuildHistory.tscn" = "../assets/Interface/BuildHistory/BuildHistory.tscn"

"res://Interface/EditModeButtons.gde" = "../assets/Interface/EditModeButtons.gde"
"res://Interface/IngameCharacterHUD.gde" = "../assets/Interface/IngameCharacterHUD.gde"
"res://Interface/Lobbies/CustomUnrankedUI.gde" = "../assets/Interface/Lobbies/CustomUnrankedUI.gde"
"res://Interface/Lobbies/OtherModesUI.tscn" = "../assets/Interface/Lobbies/OtherModesUI.tscn"
"res://Interface/OpponentRankDisplay.gde" = "../assets/Interface/OpponentRankDisplay.gde"
"res://Interface/OpponentRankDisplay.gd.remap" = "../assets/Interface/OpponentRankDisplay.gd.remap"
"res://Interface/OpponentRankDisplay.tscn" = "../assets/Interface/OpponentRankDisplay.tscn"
"res://Interface/PatchNotes.gde" = "../assets/Interface/PatchNotes.gde"
"res://Interface/PatchNotes.tscn" = "../assets/Interface/PatchNotes.tscn"
"res://Interface/PushToStorageButton.gde" = "../assets/Interface/PushToStorageButton.gde"
"res://Interface/RarityHint.gde" = "../assets/Interface/RarityHint.gde"
"res://Interface/ShopRarityChart.gde" = "../assets/Interface/ShopRarityChart.gde"
"res://Interface/ShopToolbar.gde" = "../assets/Interface/ShopToolbar.gde"
"res://Interface/Tooltips/ItemTooltip.gde" = "../assets/Interface/Tooltips/ItemTooltip.gde"

"res://Items/Item.gde" = "../assets/Items/Item.gde"
"res://pluginversion.txt" = "../assets/pluginversion.txt"

"res://Utility/BuildHistoryDB.gde" = "../assets/Utility/BuildHistoryDB.gde"
"res://Utility/CustomRules.gde" = "../assets/Utility/CustomRules.gde"

"res://Assets/Combat.png" = "../assets/Assets/Combat.png"
"res://Assets/Combat.png.import" = "../assets/Assets/Combat.png.import"
"res://Assets/Copy.png" = "../assets/Assets/Copy.png"
"res://Assets/Copy.png.import" = "../assets/Assets/Copy.png.import"

"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex" = "../assets/.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.stex"
"res://.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5" = "../assets/.import/Combat.png-88ad49c2809e77384a81bc33d532ba51.md5"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex" = "../assets/.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.stex"
"res://.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5" = "../assets/.import/Copy.png-f9434e4c62ae174b7d84e2c9c3044d7f.md5"

# "res://project.binary" = "../assets/project.binary"
